### ISSUE TITLE
Extend User with purge_crontabs

### ISSUE THREAD

**Issue by anthonyryan1** [puppetlabs/puppetlabs-cron_core#73]
## Use Case
It would be nice if we could opt-in a given user delete all unrecognized crontab entries from a given user.

Right now, when removing a crontab, it's necessary to deploy with `ensure => absent` and any crontabs that forget to get removed, can exist for an extended period on a system, while not being defined in manifests. Leading to an inconsistency between deployed state and manifests.

## Describe the Solution You Would Like
There's a bit of a precedent with:

```puppet
User {
  purge_ssh_keys => true
}
```
It would be nice to see it extended with something like: 
```puppet
User {
  purge_crontabs => true
}
```

Which, when applied to a specific user, or type defaults would instruct puppet to delete all unrecognized crontabs.

## Describe Alternatives You've Considered
Primary alternative I see is "do nothing". This is a nice-to-have feature, but the core functionality can be achieved by never forgetting to `ensure => absent` every crontab that gets removed.

It's delectably a feature request to mitigate human error, but it avoids the need for the `ensure => absent` dance before removing and lets people opt-in to a stricter synchronization between systems and manifests.

**Comment by AriaXLi** [comment]
Hi @anthonyryan1! Thank you for reporting this issue. While we agree this is likely an improvement, we do not anticipate addressing this any time soon due to other issues demanding precedence. As such, this ticket will be given the label “help-wanted”. We may revisit this at a later time.

If you are interested in submitting a patch to implement this issue, please open a pull request and link this issue. Thanks!
